# Generated by Django 2.2.20 on 2021-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_text',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
