# Generated by Django 2.2.20 on 2021-04-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210419_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.User', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_end',
            field=models.DateField(verbose_name='Завершение опроса'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_start',
            field=models.DateField(verbose_name='Начало опроса'),
        ),
    ]
